/*This command to create the Database */
CREATE DATABASE vet_clinic;

/*This command to create the table animals*/
CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) ,
    name VARCHAR(50) NOT NULL,
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL(4,2), 
    PRIMARY KEY (id)
); 

/*Add a column species type string*/
ALTER TABLE animals ADD species VARCHAR(255);