/*CReat new databse */

CREATE DATABASE clinic;

CREATE TABLE patients (
  id INT GENERATED BY DEFAULT AS IDENTITY ,
  name VARCHAR,
  date_of_birth DATE,
  PRIMARY key (id)
);

CREATE TABLE medical_histories (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  admitted_at TIMESTAMP,
  patient_id INT REFERENCES patients (id),
  status VARCHAR,
  PRIMARY KEY (id)
);

CREATE TABLE invoices (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  total_amount DECIMAL,
  generated_at TIMESTAMP,
  payed_at TIMESTAMP,
  medical_histories_id INT REFERENCES medical_histories(id),
  PRIMARY key (id)
);

CREATE TABLE treatements (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  type VARCHAR,
  name VARCHAR,
  PRIMARY KEY (id)
);

CREATE TABLE invoice_items (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  unit_price DECIMAL,
  quantity INT,
  invoice_id INT REFERENCES invoices (id),
  treatement_id INT REFERENCES treatements (id),
  PRIMARY KEY (id) 
);

CREATE TABLE histories_treatments (
history_id INT REFERENCES medical_histories(id),
treatments_id INT REFERENCES treatements(id)
);

-- Remember to add the FK indexes.
CREATE INDEX patients_index ON medical_histories(patient_id);
CREATE INDEX medical_histories_index ON invoices(medical_histories_id);
CREATE INDEX invoices_index ON invoice_items(invoice_id);
CREATE INDEX treatements_index ON invoice_items(treatement_id);
CREATE INDEX history_index ON histories_treatments(history_id);
CREATE INDEX treatment_index ON histories_treatments(treatments_id);