/*This command to create the Database */
CREATE DATABASE vet_clinic;

/*This command to create the table animals*/
CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) ,
    name VARCHAR(50) NOT NULL,
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL(4,2), 
    PRIMARY KEY (id)
); 

/*Add a column species type string*/
ALTER TABLE animals ADD species VARCHAR(255);

/*Add owners table*/
CREATE TABLE owners (
    id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) ,
    full_name VARCHAR(255) NOT NULL,
    age INT,
    PRIMARY KEY (id)
);

/*Create table species*/
CREATE TABLE species (
    id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) ,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

/*Modify table animals*/
/*Remove column species*/
ALTER TABLE animals DROP COLUMN species;

/*Add column species_id*/
ALTER TABLE animals ADD COLUMN species_id INTEGER;
ALTER TABLE animals ADD FOREIGN KEY (species_id) REFERENCES species(id);

/*Add column owner_id*/
ALTER TABLE animals ADD COLUMN owner_id INTEGER;
ALTER TABLE animals ADD FOREIGN KEY (owner_id) REFERENCES owners(id);

/*Create a table named vets*/
CREATE TABLE vets (
    id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) ,
    name VARCHAR(255) NOT NULL,
    age INT,
    date_of_graduation DATE,
    PRIMARY KEY (id)
);

/*Create a table named specializations*/
CREATE TABLE specializations (
    vet_id INTEGER ,
    species_id INTEGER ,
    PRIMARY KEY (vet_id, species_id),
    FOREIGN KEY (vet_id) REFERENCES vets(id),
    FOREIGN KEY (species_id) REFERENCES species(id)
);

/* Create a "join table" called visits*/
CREATE TABLE visits (
    animal_id INTEGER ,
    vet_id INTEGER ,
    date_of_visit DATE,
    PRIMARY KEY (animal_id, vet_id, date_of_visit),
    FOREIGN KEY (animal_id) REFERENCES animals(id),
    FOREIGN KEY (vet_id) REFERENCES vets(id)
);